apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
patches:
  - target:
      kind: Deployment
      version: v1
      group: apps
      name: pacman-kikd
      namespace: pacman
    path: external_patch.yaml


